module.exports = [
    'YYYY', // Year
    'YYYYMM', // Year_month
    'YYYYMMDD', // basic_date
    'YYYYMMDD[T]HHmmss.SSSZ', // basic_date_time
    'YYYYMMDD[T]HHmmssZ', // basic_date_time_no_millis
    'YYYYDDD', // basic_ordinal_date
    'YYYYDDD[T]HHmmss.SSSZ', // basic_ordinal_date_time
    'YYYYDDD[T]HHmmssZ', // basic_ordinal_date_time_no_millis
    'HHmmss.SSSZ', // basic_time
    'HHmmssZ', // basic_time_no_millis
    '[T]HHmmss.SSSZ', // basic_t_time
    '[T]HHmmssZ', // basic_t_time_no_millis
    'YYYY-MM', // date
    'YYYY-MM-DD', // date
    'YYYY-MM-DD[T]HH', // date_hour
    'YYYY-MM-DD[T]HH:mm', // date_hour_minute
    'YYYY-MM-DD[T]HH:mm:ss', // date_hour_minute_second
    'YYYY-MM-DD[T]HH:mm:ss.SSS', // date_hour_minute_second_fraction
    'YYYY-MM-DD[T]HH:mm:ss.SSSZZ', // date_time
    'YYYY-MM-DD[T]HH:mm:ssZZ', // date_time_no_millis
    'YYYY-MM-DD[T]HH:mmZZ', // date_time_no_second
    'HH', // hour
    'HH:mm', // hour_minute
    'HH:mm:ss', // hour_minute_second
    'HH:mm:ss.SSS', // hour_minute_second_fraction
    'YYYY-DDD', // ordinal_date
    'YYYY-DDD[T]HH:mm:ss.SSSZZ', // ordinal_date_time
    'YYYY-DDD[T]HH:mm:ssZZ', // ordinal_date_time_no_millis
    'HH:mm:ss.SSSZZ', // time
    'HH:mm:ssZZ', // time_no_millis
    '[T]HH:mm:ss.SSSZZ', // t_time
    '[T]HH:mm:ssZZ' // t_time_no_millis
];
